AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation template to create an EC2 instance with full access to S3. Parameters are Environment, InstanceType, Subnet, SecurityGroups and KeyValuePair

Parameters: 
  EnvName:
    Description: Environment
    Type: String
    Default: Dev
    AllowedValues:
        - "Dev"
        - "Uat"
        - "Prod"
  InstanceType:
    Description: Select EC2 instance type 
    Type: String
    Default: "t2.micro"
    AllowedValues: 
      - "t2.micro"
      - "m1.small"
      - "m1.large"
  Subnet:
    Description: Select the subnet ID where EC2 need to be launched
    Type: AWS::EC2::Subnet::Id
  SecurityGroups:
    Description: Select the Security Group for the instance
    Type: List<AWS::EC2::SecurityGroup::Id>
  EC2KP:
    Description: Keypair for rhe instnace
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    us-east-1:
      HVM64: "ami-0ff8a91507f77f867"
    us-west-1:
      HVM64: "ami-0bdb828fd58c52235"
    eu-west-1:
      HVM64: "ami-047bb4163c506cd98"
    ap-southeast-1:
      HVM64: "ami-08569b978cc4dfa10"
    ap-south-1:
      HVM64: "ami-0e306788ff2473ccb"      

Conditions:
  CreateDevResource: !Equals [!Ref EnvName, Dev ]
  
Resources: 
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - 
         PolicyName: "root"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: "s3:*"
                Resource: "*"

  iamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref iamRole
  
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Condition: CreateDevResource
    Properties:
      KeyName: !Ref EC2KP
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", HVM64 ] 
      InstanceType: !Ref InstanceType
      SecurityGroupIds: !Ref SecurityGroups
      IamInstanceProfile: !Ref iamInstanceProfile
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: Name
          Value: DevInstance

Outputs:
  EC2Instance:
    Condition: CreateDevResource
    Description: EC2 Instance
    Value: !Ref DevEC2Instance